{
	"maxConnection": 8192,
	"hashTableSize": 2048,
	"established": 1800,
	"synSent": 30,
	"synReceived": 20,
	"finWait": 20,
	"timeWait": 20,
	"close": 10,
	"closeWait": 20,
	"lastAck": 20,
	"unreplied": 30,
	"assured": 180,
	"generic": 10,
	"icmp": 10,
	"ftp": "checked",
	"gre": "checked",
	"h": "checked",
	"sip": "checked",
	"rtsp": "",
	"ttlAdjust": "None",
	"custom": 64,
	"inboundLayer": "checked"
}